Import('*')

# Assume that this is a gem5 extras build if this is set.
if 'TARGET_ISA' in env and env['TARGET_ISA'] == 'no':
    Return()

if 'NVMAIN_BUILD' in env:
    NVMainSourceType('src', 'Backend Source')

NVMainSource('ARMDecoder.cpp')
